---
title: "test"
author: "BastianEichmueller"
date: "2021-02-19"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Luad analysis

```{r, warning=FALSE}
library(tidyverse)
```


```{r}
dat <- read_tsv("data/luad_tcga_pan_can_atlas_2018_clinical_data.tsv") %>% 
  select(
    where(
      ~sum(!is.na(.x)) > 0
    )
  ) %>% 
  tibble(.name_repair = "universal")

names(dat) <- tolower(gsub("\\.", "_", names(dat)))
head(dat)
```

```{r}
d <- transmute(dat,
               diagnosis_age = round(-birth_from_initial_pathologic_diagnosis_date/365.24),
               sex = factor(sex),
               race_category = factor(race_category),
               american_joint_committee_on_cancer_tumor_stage_code = factor(american_joint_committee_on_cancer_tumor_stage_code),
               mutation_count
               )

d
```

```{r}
with(d,
     table(round(diagnosis_age, digits = -1), sex)
)

```

```{r}
with(d,
     table(race_category, american_joint_committee_on_cancer_tumor_stage_code)
     )
```

```{r}
d %>% 
  ggplot(aes(x=american_joint_committee_on_cancer_tumor_stage_code, col=sex))+
  geom_bar(position = "dodge")
```

```{r}
with(d,
     chisq.test(sex, american_joint_committee_on_cancer_tumor_stage_code)
)

```

```{r}
d %>% 
  lm(mutation_count~sex+diagnosis_age+american_joint_committee_on_cancer_tumor_stage_code, 
     data=.)
```

```{r}
d %>% 
  ggplot(aes(x=diagnosis_age, y=mutation_count))+
  geom_point()
```

